### PR TITLE
feat: Update TS SDK Version

### PR DESCRIPTION
**Pull request by gautamomento**
```
> momento-typescript-example@1.0.0 example
> tsc && node dist/index.js

Storing key=key, value=value, ttl=60
cache hit: value
success!!
```

### CODE REVIEW

**Comment by bruuuuuuuce** [comment]
@gautamomento you are logged into momentos npm registry, so it pulled the ts version from that. But that is not publicly available, which is why the build is failing. If you nuke the package-lock.json and your ~/.npmrc file, and do an `npm install` that should fix it

**Comment by gautamomento** [comment]
Should we be checking in `package-lock.json`?

**Comment by danielamiao** [comment]
> Should we be checking in `package-lock.json`?

I think it's optional, but more importantly you should try the thing Matt suggested and check in the correct file, not from the momento npm registry.

**Comment by bruuuuuuuce** [comment]
imo we should, that way the customers can `npm ci`, and install the exact versions of all the deps that we have. Generally its best practice to check this in

**Comment by gautamomento** [comment]
For whatever reason  I can't get this to work. It is regenerating the same one with momento buckets etc.

**Comment by gautamomento** [comment]
Can one of you try to pull this branch in and see if you are able to get around this?

**Comment by danielamiao** [comment]
Yes same, i get 

```
npm notice 
npm notice New major version of npm available! 7.21.1 -> 8.3.2
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.3.2
npm notice Run npm install -g npm@8.3.2 to update!
npm notice 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@momento%2fsdk - Not found
npm ERR! 404 
npm ERR! 404  '@momento/sdk@0.4.3' is not in the npm registry.
```

**Comment by gautamomento** [comment]
The SDK is there:
https://momento.jfrog.io/ui/repos/tree/General/npm-public/@momento/sdk/-/@momento/sdk-0.4.3.tgz

Probably need this before npm install
`npm config set @momento:registry https://momento.jfrog.io/artifactory/api/npm/npm-public/`

**Pull request closed without merging**
